In [2]:
import dezero
import dezero.functions as F
import dezero.layers as L
from dezero.models import Model

In [16]:
class BiRNN(Model):
    def __init__(self, hidden_size):
        super().__init__()
        self.f_rnn = L.RNN(hidden_size)
        self.b_rnn = L.RNN(hidden_size)
    
    def reset_state(self):
        self.f_rnn.reset_state()
        self.b_rnn.reset_state()
    
    def forward(self, inputs):
        f_hs, b_hs = [], []
        for x, t in inputs:
            f_hs.append(self.f_rnn(x))
        

In [15]:
model = BiRNN(100)
model(train_set)

TypeError: cannot create weak reference to 'int' object

In [3]:
train_set = dezero.datasets.SinCurve(train=True)
seqlen = len(train_set)

x, y = [], []
for i in range(5):
    x.append(train_set[i][0])
    y.append(train_set[i][1])

x, y

([array([-0.02592524]),
  array([0.02101364]),
  array([-0.02151476]),
  array([-0.01227188]),
  array([0.01011053])],
 [array([0.02101364]),
  array([-0.02151476]),
  array([-0.01227188]),
  array([0.01011053]),
  array([0.00587657])])

In [7]:
train_set[0][0].reshape(1,1)

array([[0.03308969]])

TypeError: cannot create weak reference to 'NoneType' object